### ISSUE TITLE
No such file or directory: 'wmt14_en_de/tmp/dev.de.ori'?

### ISSUE THREAD

**Issue by zjplab** [XuezheMax/flowseq#6]
I used the script on fairseq to downlaod wmt14 data:
`bash prepare-wmt14en2de.sh  --icml17` 

Output file structure:
![image](https://user-images.githubusercontent.com/16349466/70937046-aa2f9780-2011-11ea-97d3-5a0938404a66.png)

But when I run the training program, it shows an error:
```Traceback (most recent call last):
  File "/content/flowseq/experiments/distributed.py", line 94, in run
    single_process_main(args)
  File "/content/flowseq/experiments/nmt.py", line 763, in main
    train_iter, val_iter, test_iter = init_dataloader(args, dataset)
  File "/content/flowseq/experiments/nmt.py", line 290, in init_dataloader
    bucket_data=args.bucket_batch, multi_scale=args.length_unit)
  File "/content/flowseq/flownmt/data/dataloader.py", line 291, in __init__
    self.data_size, self.data = self.get_dataset()
  File "/content/flowseq/flownmt/data/dataloader.py", line 337, in get_dataset
    ftgt_ori = None if tgt_ori_path is None else codecs.open(tgt_ori_path, "r", encoding="utf-8")
  File "/usr/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'wmt14_en_de/tmp/dev.de.ori
```

**Comment by XuezheMax** [comment]
Please contact fairseq for this issues.
Thanks.

**Comment by DeNeutoy** [comment]
@XuezheMax - this is not a fairseq issue - prepare-wmt14en2de.sh does not create any files called `*.ori`. Because of the way these files are prepared by moses, it is difficult to recreate them (the bpe files are cleaned, meaning we cannot just use the raw `{train,dev,test}.{en, de}` files). Would you be able to share how you produced these files?

**Comment by DeNeutoy** [comment]
In the meantime, I first cleaned the validation data (without peforming bpe segmentation on it) using this line https://github.com/pytorch/fairseq/blob/master/examples/translation/prepare-wmt14en2de.sh#L138

and then ran the BPE encoding script. This meant that both the word tokenized version and the bpe tokenized version get the same data filtered out (as it was done before). I then just copied the files to `valid.{lang}.ori`. I don't know if this is officially correct, because the data that is filtered is different depending on whether you run the filtering script before or after doing BPE, but 🤷‍♂

**Comment by violet-zct** [comment]
@DeNeutoy *.ori are just the original tokenized files, we use them to compute the BLEU score. You can just put your original dev/test original tokenized files in the corresponding directories.

**Comment by DeNeutoy** [comment]
@violet-zct you actually can't do that, I don't think - because the `prepare-wmt14en2de.sh` script does two things,

1) BPE encodes {train, dev, test}.
2) cleans the BPE encoded files, using the moses script, which reduces the number of examples in {train,dev}. 

So, once the final dataset is produced, it does not have the same number of dev/test data points as in the original (because it has been cleaned), meaning that just putting the original files in the right place doesn't work.

**Comment by violet-zct** [comment]
@DeNeutoy You can simply `sed -r 's/(@@ )|(@@ ?$)//g'` to restore the original segmentation of ``the '' dev file you are using from the BPE version.

**Comment by DeNeutoy** [comment]
Oh great, thanks!
